export const FETCHING_LIST_USERS = 'FETCHING_LIST_USERS';
export const FETCHING_LIST_USERS_SUCCESS = 'FETCHING_LIST_USERS_SUCCESS';
export const FETCHING_LIST_USERS_FAIL = 'FETCHING_LIST_USERS_FAIL';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';