export const FETCHING_LIST_USERS = 'FETCHING_LIST_USERS';
export const FETCHING_LIST_USERS_SUCCESS = 'FETCHING_LIST_USERS_SUCCESS';
export const FETCHING_LIST_USERS_FAIL = 'FETCHING_LIST_USERS_FAIL';

export const FETCHING_USER = 'FETCHING_USER';
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS';
export const FETCHING_USER_FAIL = 'FETCHING_USER_FAIL';

export const FETCHING_LIST_PRODUCTS = 'FETCHING_LIST_PRODUCTS'
export const FETCHING_LIST_PRODUCTS_SUCCESS = 'FETCHING_LIST_PRODUCTS_SUCCESS'
export const FETCHING_LIST_PRODUCTS_FAIL = 'FETCHING_LIST_PRODUCTS_FAIL'

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART'; 
